import './bootstrap';
import Alpine from 'alpinejs';
import morph from '@alpinejs/morph';
import { initTextareaAutosize } from './utils/textarea-autosize';
import { registerAlpineStores } from './stores/alpine-stores';
import { initBoot } from './boot';

import { autoSaveDatePicker } from './components/auto-save-date-picker';
import { autoSaveField } from './components/auto-save-field';
import { autoSaveForm } from './components/auto-save-form';
import { sortableList } from './components/sortable-list';
import { sortableKanban } from './components/sortable-kanban';
import { filterManager } from './components/filter-manager';
import { markdownEditor } from './components/markdown-editor';
import { privacyToggle } from './components/privacy-toggle';
import { recurrenceSettings } from './components/recurrence-settings';
import { confirmDialog } from './components/confirm-dialog';
import { datePicker } from './components/date-picker';
import { keyboardShortcuts } from './components/keyboard-shortcuts';
import { analyticsChart } from './components/analytics-chart';
import { analyticsBoard } from './components/analytics-board';
import { weeklyChart } from './components/weekly-chart';
import { widgetConfigurator } from './components/widget-configurator';
import { agreementManager } from './components/agreement-manager';
import { inlineSelect } from './components/inline-select';
import { liveCounter } from './components/live-counter';
import { calendarEventActions } from './components/calendar-event-actions';
import { emailActions } from './components/email-actions';
import { emailPage } from './components/email-page';
import { jiraPage } from './components/jira-page';
import { jiraActions } from './components/jira-actions';
import { syncButton } from './components/sync-button';
import { systemNotification } from './components/system-notification';
import { refreshable } from './components/refreshable';
import { activityInput } from './components/activity-input';
import { followUpActions } from './components/follow-up-actions';
import { tagEditor } from './components/tag-editor';
import { audioRecorder } from './components/audio-recorder';
import { extractionReview } from './components/extraction-review';
import { transcriptionViewer } from './components/transcription-viewer';
import { apiTokenManager } from './components/api-token-manager';
import { inlineAutoSave } from './components/inline-auto-save';
import { teamMemberFilter } from './components/team-member-filter';
import { createModal } from './components/create-modal';
import { toggleState } from './components/toggle-state';
import { themeToggle } from './components/theme-toggle';
import { popperDropdown } from './components/popper-dropdown';
import { modalComponent } from './components/modal-component';
import { bulkSelect } from './components/bulk-select';
import { storageManager } from './components/storage-manager';
import { jiraDashboardWidget } from './components/jira-dashboard-widget';
import { taskActions } from './components/task-actions';
import { followUpPage } from './components/follow-up-page';
import { meetingTypeChanger } from './components/meeting-type-changer';
import { meetingStatusTransition } from './components/meeting-status-transition';
import { meetingAttendees } from './components/meeting-attendees';
import { meetingTabs } from './components/meeting-tabs';
import { meetingPrepItems } from './components/meeting-prep-items';
import { sidebarNav } from './components/sidebar-nav';
import { settingsTimezone } from './components/settings-timezone';
import { settingsDashboardWidgets } from './components/settings-dashboard-widgets';
import { settingsSpeechService } from './components/settings-speech-service';
import { settingsSystemHealth } from './components/settings-system-health';
import { settingsDataPruning } from './components/settings-data-pruning';
import { userDropdown } from './components/user-dropdown';
import { appHeaderMenu } from './components/app-header-menu';
import { recordingDelete } from './components/recording-delete';
import { flashMessage } from './components/flash-message';

declare global {
    interface Window {
        Alpine: typeof Alpine;
    }
}

Alpine.data('autoSaveDatePicker', autoSaveDatePicker as Parameters<typeof Alpine.data>[1]);
Alpine.data('autoSaveField', autoSaveField as Parameters<typeof Alpine.data>[1]);
Alpine.data('autoSaveForm', autoSaveForm as Parameters<typeof Alpine.data>[1]);
Alpine.data('sortableList', sortableList as Parameters<typeof Alpine.data>[1]);
Alpine.data('sortableKanban', sortableKanban as Parameters<typeof Alpine.data>[1]);
Alpine.data('filterManager', filterManager as Parameters<typeof Alpine.data>[1]);
Alpine.data('markdownEditor', markdownEditor as Parameters<typeof Alpine.data>[1]);
Alpine.data('privacyToggle', privacyToggle as Parameters<typeof Alpine.data>[1]);
Alpine.data('recurrenceSettings', recurrenceSettings as Parameters<typeof Alpine.data>[1]);
Alpine.data('confirmDialog', confirmDialog as Parameters<typeof Alpine.data>[1]);
Alpine.data('datePicker', datePicker as Parameters<typeof Alpine.data>[1]);
Alpine.data('keyboardShortcuts', keyboardShortcuts as Parameters<typeof Alpine.data>[1]);
Alpine.data('analyticsChart', analyticsChart as Parameters<typeof Alpine.data>[1]);
Alpine.data('analyticsBoard', analyticsBoard as Parameters<typeof Alpine.data>[1]);
Alpine.data('weeklyChart', weeklyChart as Parameters<typeof Alpine.data>[1]);
Alpine.data('widgetConfigurator', widgetConfigurator as Parameters<typeof Alpine.data>[1]);
Alpine.data('agreementManager', agreementManager as Parameters<typeof Alpine.data>[1]);
Alpine.data('inlineSelect', inlineSelect as Parameters<typeof Alpine.data>[1]);
Alpine.data('liveCounter', liveCounter as Parameters<typeof Alpine.data>[1]);
Alpine.data('calendarEventActions', calendarEventActions as Parameters<typeof Alpine.data>[1]);
Alpine.data('emailActions', emailActions as Parameters<typeof Alpine.data>[1]);
Alpine.data('emailPage', emailPage as Parameters<typeof Alpine.data>[1]);
Alpine.data('jiraPage', jiraPage as Parameters<typeof Alpine.data>[1]);
Alpine.data('jiraActions', jiraActions as Parameters<typeof Alpine.data>[1]);
Alpine.data('syncButton', syncButton as Parameters<typeof Alpine.data>[1]);
Alpine.data('systemNotification', systemNotification as Parameters<typeof Alpine.data>[1]);
Alpine.data('refreshable', refreshable as Parameters<typeof Alpine.data>[1]);
Alpine.data('activityInput', activityInput as Parameters<typeof Alpine.data>[1]);
Alpine.data('followUpActions', followUpActions as Parameters<typeof Alpine.data>[1]);
Alpine.data('tagEditor', tagEditor as Parameters<typeof Alpine.data>[1]);
Alpine.data('audioRecorder', audioRecorder as Parameters<typeof Alpine.data>[1]);
Alpine.data('extractionReview', extractionReview as Parameters<typeof Alpine.data>[1]);
Alpine.data('transcriptionViewer', transcriptionViewer as Parameters<typeof Alpine.data>[1]);
Alpine.data('apiTokenManager', apiTokenManager as Parameters<typeof Alpine.data>[1]);
Alpine.data('inlineAutoSave', inlineAutoSave as Parameters<typeof Alpine.data>[1]);
Alpine.data('teamMemberFilter', teamMemberFilter as Parameters<typeof Alpine.data>[1]);
Alpine.data('createModal', createModal as Parameters<typeof Alpine.data>[1]);
Alpine.data('toggleState', toggleState as Parameters<typeof Alpine.data>[1]);
Alpine.data('themeToggle', themeToggle as Parameters<typeof Alpine.data>[1]);
Alpine.data('popperDropdown', popperDropdown as Parameters<typeof Alpine.data>[1]);
Alpine.data('modalComponent', modalComponent as Parameters<typeof Alpine.data>[1]);
Alpine.data('bulkSelect', bulkSelect as Parameters<typeof Alpine.data>[1]);
Alpine.data('storageManager', storageManager as Parameters<typeof Alpine.data>[1]);
Alpine.data('jiraDashboardWidget', jiraDashboardWidget as Parameters<typeof Alpine.data>[1]);
Alpine.data('taskActions', taskActions as Parameters<typeof Alpine.data>[1]);
Alpine.data('followUpPage', followUpPage as Parameters<typeof Alpine.data>[1]);
Alpine.data('meetingTypeChanger', meetingTypeChanger as Parameters<typeof Alpine.data>[1]);
Alpine.data('meetingStatusTransition', meetingStatusTransition as Parameters<typeof Alpine.data>[1]);
Alpine.data('meetingAttendees', meetingAttendees as Parameters<typeof Alpine.data>[1]);
Alpine.data('meetingTabs', meetingTabs as Parameters<typeof Alpine.data>[1]);
Alpine.data('meetingPrepItems', meetingPrepItems as Parameters<typeof Alpine.data>[1]);
Alpine.data('sidebarNav', sidebarNav as Parameters<typeof Alpine.data>[1]);
Alpine.data('settingsTimezone', settingsTimezone as Parameters<typeof Alpine.data>[1]);
Alpine.data('settingsDashboardWidgets', settingsDashboardWidgets as Parameters<typeof Alpine.data>[1]);
Alpine.data('settingsSpeechService', settingsSpeechService as Parameters<typeof Alpine.data>[1]);
Alpine.data('settingsSystemHealth', settingsSystemHealth as Parameters<typeof Alpine.data>[1]);
Alpine.data('settingsDataPruning', settingsDataPruning as Parameters<typeof Alpine.data>[1]);
Alpine.data('userDropdown', userDropdown as Parameters<typeof Alpine.data>[1]);
Alpine.data('appHeaderMenu', appHeaderMenu as Parameters<typeof Alpine.data>[1]);
Alpine.data('recordingDelete', recordingDelete as Parameters<typeof Alpine.data>[1]);
Alpine.data('flashMessage', flashMessage as Parameters<typeof Alpine.data>[1]);

window.Alpine = Alpine;

Alpine.plugin(morph);
registerAlpineStores(Alpine);
Alpine.start();
initTextareaAutosize();
initBoot();
